services:
  spotify-wordpress-tracker:
    build: .
    container_name: spotify-wordpress-tracker
    env_file:
      - .env
    volumes:
      # live editing
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true